# Generated by Django 5.0.7 on 2025-09-06 21:55

import apps.projects.models.project_model
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("key", models.CharField(max_length=10)),
                ("description", models.TextField(blank=True)),
                (
                    "methodology",
                    models.CharField(
                        choices=[
                            ("scrum", "Scrum"),
                            ("kanban", "Kanban"),
                            ("waterfall", "Waterfall"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="scrum",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("active", "Active"),
                            ("on_hold", "On Hold"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("archived", "Archived"),
                        ],
                        default="planning",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("estimated_hours", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "attachments",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.projects.models.project_model.project_file_path,
                    ),
                ),
                ("project_settings", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="led_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "db_table": "projects",
                "ordering": ["-created_at"],
                "unique_together": {("workspace", "key")},
            },
        ),
        migrations.CreateModel(
            name="ProjectArchive",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("completed", "Project Completed"),
                            ("cancelled", "Project Cancelled"),
                            ("on_hold", "Project On Hold"),
                            ("merged", "Merged with Another Project"),
                            ("obsolete", "Project Obsolete"),
                            ("other", "Other Reason"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Additional details about why the project was archived",
                    ),
                ),
                ("archived_at", models.DateTimeField(auto_now_add=True)),
                (
                    "final_statistics",
                    models.JSONField(
                        default=dict,
                        help_text="Final project statistics (issues, sprints, team members, etc.)",
                    ),
                ),
                (
                    "backup_data",
                    models.JSONField(
                        default=dict, help_text="Backup of critical project data"
                    ),
                ),
                ("can_be_restored", models.BooleanField(default=True)),
                (
                    "auto_delete_after_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Automatically delete after X days (null = never delete)",
                        null=True,
                    ),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archived_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archive_info",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Archive",
                "verbose_name_plural": "Project Archives",
                "db_table": "project_archives",
                "ordering": ["-archived_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sprint_duration",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "1 Week"),
                            (2, "2 Weeks"),
                            (3, "3 Weeks"),
                            (4, "4 Weeks"),
                        ],
                        default=2,
                        help_text="Sprint duration in weeks",
                    ),
                ),
                ("auto_close_sprints", models.BooleanField(default=True)),
                (
                    "estimation_type",
                    models.CharField(
                        choices=[
                            ("story_points", "Story Points"),
                            ("hours", "Hours"),
                            ("t_shirt", "T-Shirt Sizes"),
                        ],
                        default="story_points",
                        max_length=20,
                    ),
                ),
                (
                    "story_point_scale",
                    models.JSONField(
                        default=list,
                        help_text="Fibonacci sequence: [1, 2, 3, 5, 8, 13, 21]",
                    ),
                ),
                ("enable_time_tracking", models.BooleanField(default=True)),
                ("require_time_logging", models.BooleanField(default=False)),
                ("enable_sub_tasks", models.BooleanField(default=True)),
                ("email_notifications", models.BooleanField(default=True)),
                ("slack_notifications", models.BooleanField(default=False)),
                ("slack_webhook_url", models.URLField(blank=True)),
                ("restrict_issue_visibility", models.BooleanField(default=False)),
                ("require_approval_for_changes", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuration",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Configuration",
                "verbose_name_plural": "Project Configurations",
                "db_table": "project_configurations",
            },
        ),
        migrations.CreateModel(
            name="WorkflowStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("to_do", "To Do"),
                            ("in_progress", "In Progress"),
                            ("done", "Done"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("color", models.CharField(default="#DFE1E6", max_length=7)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_initial", models.BooleanField(default=False)),
                ("is_final", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_statuses",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Status",
                "verbose_name_plural": "Workflow Statuses",
                "db_table": "workflow_statuses",
                "ordering": ["order", "name"],
                "unique_together": {("project", "name")},
            },
        ),
        migrations.CreateModel(
            name="IssueType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("epic", "Epic"),
                            ("story", "Story"),
                            ("task", "Task"),
                            ("bug", "Bug"),
                            ("improvement", "Improvement"),
                            ("sub_task", "Sub-task"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("color", models.CharField(default="#0052CC", max_length=7)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issue_types",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Issue Type",
                "verbose_name_plural": "Issue Types",
                "db_table": "issue_types",
                "ordering": ["name"],
                "unique_together": {("project", "name")},
            },
        ),
        migrations.CreateModel(
            name="ProjectTeamMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("project_manager", "Project Manager"),
                            ("tech_lead", "Tech Lead"),
                            ("developer", "Developer"),
                            ("designer", "Designer"),
                            ("qa_engineer", "QA Engineer"),
                            ("business_analyst", "Business Analyst"),
                            ("stakeholder", "Stakeholder"),
                        ],
                        default="developer",
                        max_length=30,
                    ),
                ),
                ("permissions", models.JSONField(default=dict)),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_members",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Team Member",
                "verbose_name_plural": "Project Team Members",
                "db_table": "project_team_members",
                "ordering": ["-joined_at"],
                "unique_together": {("project", "user")},
            },
        ),
        migrations.CreateModel(
            name="WorkflowTransition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("conditions", models.JSONField(default=dict)),
                ("validators", models.JSONField(default=dict)),
                ("post_functions", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_transitions",
                        to="projects.workflowstatus",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_transitions",
                        to="projects.project",
                    ),
                ),
                (
                    "to_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_transitions",
                        to="projects.workflowstatus",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Transition",
                "verbose_name_plural": "Workflow Transitions",
                "db_table": "workflow_transitions",
                "ordering": ["name"],
                "unique_together": {("project", "from_status", "to_status")},
            },
        ),
    ]
