# Generated by Django 5.0.7 on 2025-09-07 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectconfiguration",
            name="id",
        ),
        migrations.AlterField(
            model_name="projectconfiguration",
            name="project",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="configuration",
                serialize=False,
                to="projects.project",
            ),
        ),
    ]
