# Generated by Django 5.0.7 on 2025-10-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_board_boardcolumn_issue_issueattachment_issuecomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectconfiguration',
            name='slack_webhook_url',
            field=models.URLField(blank=True, help_text='Slack webhook URL for notifications (optional)', null=True),
        ),
    ]
