# Generated by Django 5.0.7 on 2025-10-10 14:22

import apps.reporting.models.report_snapshot_model
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('projects', '0003_board_boardcolumn_issue_issueattachment_issuecomment_and_more'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('transitioned', 'Transitioned'), ('commented', 'Commented'), ('attached', 'Attached'), ('linked', 'Linked'), ('assigned', 'Assigned'), ('sprint_added', 'Added to Sprint'), ('sprint_removed', 'Removed from Sprint'), ('archived', 'Archived'), ('restored', 'Restored')], max_length=20)),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('object_repr', models.CharField(max_length=500)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='activity_lo_user_id_d23b30_idx'), models.Index(fields=['project', 'created_at'], name='activity_lo_project_80b048_idx'), models.Index(fields=['action_type', 'created_at'], name='activity_lo_action__9b73de_idx'), models.Index(fields=['content_type', 'object_id'], name='activity_lo_content_edc5bf_idx')],
            },
        ),
        migrations.CreateModel(
            name='DiagramCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diagram_type', models.CharField(choices=[('workflow', 'Workflow Diagram'), ('dependency', 'Dependency Diagram'), ('roadmap', 'Roadmap'), ('uml', 'UML Diagram'), ('architecture', 'Architecture Diagram')], max_length=20)),
                ('diagram_data', models.TextField()),
                ('format', models.CharField(choices=[('svg', 'SVG'), ('png', 'PNG'), ('json', 'JSON')], default='svg', max_length=10)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('cache_key', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
                ('access_count', models.IntegerField(default=0)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_diagrams', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagram_caches', to='projects.project')),
            ],
            options={
                'verbose_name': 'Diagram Cache',
                'verbose_name_plural': 'Diagram Caches',
                'db_table': 'diagram_caches',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['project', 'diagram_type'], name='diagram_cac_project_a17137_idx'), models.Index(fields=['cache_key'], name='diagram_cac_cache_k_da0e46_idx'), models.Index(fields=['expires_at'], name='diagram_cac_expires_3db46b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReportSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('velocity', 'Velocity Chart'), ('sprint_summary', 'Sprint Summary'), ('team_metrics', 'Team Metrics'), ('cfd', 'Cumulative Flow Diagram'), ('burndown', 'Burndown Chart'), ('custom', 'Custom Report')], max_length=20)),
                ('report_data', models.JSONField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('csv_file', models.FileField(blank=True, null=True, upload_to=apps.reporting.models.report_snapshot_model.report_csv_path)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_snapshots', to='projects.project')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_snapshots', to='projects.sprint')),
            ],
            options={
                'verbose_name': 'Report Snapshot',
                'verbose_name_plural': 'Report Snapshots',
                'db_table': 'report_snapshots',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['project', 'report_type'], name='report_snap_project_29effa_idx'), models.Index(fields=['sprint'], name='report_snap_sprint__33f746_idx'), models.Index(fields=['generated_at'], name='report_snap_generat_c7bc1d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('filter_criteria', models.JSONField(default=dict)),
                ('is_public', models.BooleanField(default=False)),
                ('shared_with_team', models.BooleanField(default=False)),
                ('use_count', models.IntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_filters', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_filters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Filter',
                'verbose_name_plural': 'Saved Filters',
                'db_table': 'saved_filters',
                'ordering': ['-last_used_at', '-created_at'],
                'indexes': [models.Index(fields=['user', 'project'], name='saved_filte_user_id_1da2b3_idx'), models.Index(fields=['is_public'], name='saved_filte_is_publ_76627c_idx')],
                'unique_together': {('user', 'project', 'name')},
            },
        ),
    ]
