# Generated by Django 5.0.7 on 2025-11-17 10:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        (
            "organizations",
            "0004_rename_organizatio_token_idx_organizatio_token_779f11_idx_and_more",
        ),
        ("projects", "0004_make_slack_webhook_optional"),
        ("reporting", "0003_change_diagram_data_to_jsonfield"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="activitylog",
            new_name="activity_lo_organiz_0b4cc8_idx",
            old_name="activity_lo_organiz_idx",
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["workspace", "created_at"],
                name="activity_lo_workspa_a8c8f5_idx",
            ),
        ),
    ]
