# Generated by Django 5.0.7 on 2025-11-20 06:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0003_add_author_name_index_to_github_commit"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="githubcommit",
            new_name="github_comm_author__2a2728_idx",
            old_name="github_comm_author__idx",
        ),
    ]
