# Generated by Django 5.0.7 on 2025-11-02 01:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_id', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_chat_conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('context_issues', models.JSONField(blank=True, default=list)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('prompt_tokens', models.IntegerField(blank=True, null=True)),
                ('completion_tokens', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.chatconversation')),
            ],
            options={
                'db_table': 'ai_chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssueEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_id', models.UUIDField(db_index=True, unique=True)),
                ('project_id', models.UUIDField(db_index=True)),
                ('vector_id', models.CharField(max_length=255, unique=True)),
                ('namespace', models.CharField(default='issues', max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('content_hash', models.CharField(help_text='Hash of title+description', max_length=64)),
                ('is_indexed', models.BooleanField(default=False)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_issue_embeddings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['issue_id'], name='ai_issue_em_issue_i_0f70b0_idx'), models.Index(fields=['project_id', 'is_indexed'], name='ai_issue_em_project_cf00dd_idx')],
            },
        ),
        migrations.CreateModel(
            name='SummaryCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary_type', models.CharField(choices=[('issue_discussion', 'Issue Discussion'), ('sprint_retrospective', 'Sprint Retrospective'), ('project_status', 'Project Status'), ('release_notes', 'Release Notes')], max_length=50)),
                ('object_id', models.UUIDField()),
                ('summary_text', models.TextField()),
                ('summary_length', models.CharField(default='medium', max_length=20)),
                ('content_hash', models.CharField(help_text='Hash of source content', max_length=64)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'ai_summary_cache',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['user', 'is_active'], name='ai_chat_con_user_id_b2c6b3_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['project_id'], name='ai_chat_con_project_51d22b_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='ai_chat_mes_convers_98666d_idx'),
        ),
        migrations.AddIndex(
            model_name='summarycache',
            index=models.Index(fields=['content_type', 'object_id'], name='ai_summary__content_7fac59_idx'),
        ),
        migrations.AddIndex(
            model_name='summarycache',
            index=models.Index(fields=['is_valid', 'expires_at'], name='ai_summary__is_vali_ca9569_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='summarycache',
            unique_together={('content_type', 'object_id', 'summary_type', 'summary_length')},
        ),
    ]
