# Generated by Django 5.0.7 on 2025-11-02 01:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_type', models.CharField(choices=[('effort_prediction', 'Effort Prediction'), ('sprint_duration', 'Sprint Duration Estimation'), ('story_points', 'Story Points Recommendation'), ('task_assignment', 'Task Assignment Suggestion'), ('risk_detection', 'Risk Detection'), ('anomaly_detection', 'Anomaly Detection')], max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('training', 'Training'), ('active', 'Active'), ('deprecated', 'Deprecated'), ('failed', 'Failed')], default='training', max_length=20)),
                ('model_file', models.FileField(blank=True, null=True, upload_to='ml_models/')),
                ('model_path', models.CharField(blank=True, help_text='Path to model file if not using FileField', max_length=500)),
                ('training_samples', models.IntegerField(default=0)),
                ('training_date', models.DateTimeField(auto_now_add=True)),
                ('accuracy_score', models.FloatField(blank=True, null=True)),
                ('precision_score', models.FloatField(blank=True, null=True)),
                ('recall_score', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('mae', models.FloatField(blank=True, help_text='Mean Absolute Error', null=True)),
                ('rmse', models.FloatField(blank=True, help_text='Root Mean Squared Error', null=True)),
                ('r2_score', models.FloatField(blank=True, help_text='R-squared Score', null=True)),
                ('hyperparameters', models.JSONField(blank=True, default=dict)),
                ('feature_importance', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trained_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ml_models',
                'ordering': ['-training_date'],
            },
        ),
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_data', models.JSONField(help_text='Input features used for prediction')),
                ('predicted_value', models.FloatField()),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('prediction_range_min', models.FloatField(blank=True, null=True)),
                ('prediction_range_max', models.FloatField(blank=True, null=True)),
                ('actual_value', models.FloatField(blank=True, null=True)),
                ('outcome_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('project_id', models.UUIDField(blank=True, null=True)),
                ('issue_id', models.UUIDField(blank=True, null=True)),
                ('sprint_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='ml.mlmodel')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ml_prediction_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnomalyDetection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anomaly_type', models.CharField(help_text='Type of anomaly detected', max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='detected', max_length=20)),
                ('project_id', models.UUIDField(blank=True, null=True)),
                ('sprint_id', models.UUIDField(blank=True, null=True)),
                ('affected_metric', models.CharField(max_length=100)),
                ('expected_value', models.FloatField(blank=True, null=True)),
                ('actual_value', models.FloatField()),
                ('deviation_score', models.FloatField(help_text='How far from normal (in standard deviations)')),
                ('description', models.TextField()),
                ('possible_causes', models.JSONField(blank=True, default=list)),
                ('mitigation_suggestions', models.JSONField(blank=True, default=list)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_anomalies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ml_anomaly_detections',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project_id', 'status'], name='ml_anomaly__project_122a36_idx'), models.Index(fields=['severity', 'created_at'], name='ml_anomaly__severit_8774fd_idx'), models.Index(fields=['anomaly_type'], name='ml_anomaly__anomaly_8bc71f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='mlmodel',
            index=models.Index(fields=['model_type', 'status'], name='ml_models_model_t_426c2a_idx'),
        ),
        migrations.AddIndex(
            model_name='mlmodel',
            index=models.Index(fields=['training_date'], name='ml_models_trainin_41bcb9_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionhistory',
            index=models.Index(fields=['model', 'created_at'], name='ml_predicti_model_i_4442e3_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionhistory',
            index=models.Index(fields=['project_id'], name='ml_predicti_project_e35a16_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionhistory',
            index=models.Index(fields=['issue_id'], name='ml_predicti_issue_i_5e2cc7_idx'),
        ),
    ]
