# Generated by Django 5.0.7 on 2025-11-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mlmodel",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Whether this model is currently active for predictions",
            ),
        ),
        migrations.AddField(
            model_name="mlmodel",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional metadata (accuracy, samples_count, project_id, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="mlmodel",
            name="name",
            field=models.CharField(
                blank=True, help_text="Human-readable model name", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="mlmodel",
            name="s3_bucket",
            field=models.CharField(
                blank=True,
                help_text="S3 bucket name where model is stored",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="mlmodel",
            name="s3_key",
            field=models.CharField(
                blank=True, help_text="S3 object key for the model file", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="mlmodel",
            name="model_path",
            field=models.CharField(
                blank=True, help_text="S3 key path to model file", max_length=500
            ),
        ),
    ]
