# Generated by Django 5.0.7 on 2025-10-10 19:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0003_update_invitation_and_membership"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="organizationinvitation",
            new_name="organizatio_token_779f11_idx",
            old_name="organizatio_token_idx",
        ),
        migrations.RenameIndex(
            model_name="organizationinvitation",
            new_name="organizatio_email_a6c4d7_idx",
            old_name="organizatio_email_idx",
        ),
        migrations.RenameIndex(
            model_name="organizationinvitation",
            new_name="organizatio_status_00e3f6_idx",
            old_name="organizatio_status_idx",
        ),
    ]
