# Generated by Django 5.0.7 on 2025-11-02 01:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectNotificationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_id', models.UUIDField(unique=True)),
                ('slack_webhook_url', models.URLField(blank=True)),
                ('slack_channel', models.CharField(blank=True, max_length=100)),
                ('slack_enabled', models.BooleanField(default=False)),
                ('notify_on_issue_create', models.BooleanField(default=True)),
                ('notify_on_issue_update', models.BooleanField(default=False)),
                ('notify_on_status_change', models.BooleanField(default=True)),
                ('notify_on_sprint_event', models.BooleanField(default=True)),
                ('notify_on_anomaly', models.BooleanField(default=True)),
                ('custom_settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'project_notification_settings',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_enabled', models.BooleanField(default=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('slack_enabled', models.BooleanField(default=False)),
                ('notification_types', models.JSONField(default=dict, help_text='Dictionary of notification types and their enabled status')),
                ('digest_enabled', models.BooleanField(default=False, help_text='Receive daily digest instead of real-time')),
                ('digest_time', models.TimeField(blank=True, help_text='Time to send daily digest', null=True)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('issue_assigned', 'Issue Assigned'), ('issue_updated', 'Issue Updated'), ('issue_commented', 'Issue Commented'), ('status_changed', 'Status Changed'), ('sprint_started', 'Sprint Started'), ('sprint_completed', 'Sprint Completed'), ('deadline_approaching', 'Deadline Approaching'), ('mention', 'Mentioned'), ('ai_insight', 'AI Insight'), ('anomaly_detected', 'Anomaly Detected')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('link', models.URLField(blank=True, help_text='Link to related resource')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('slack_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_583549_idx'), models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_2c3905_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_19df93_idx')],
            },
        ),
    ]
